""" from micropython import const

# Adjustable parameters
DEBUG = const(False)
SPARSE_SENSOR_READING = const(True)

# Fixed parameters for sensor and motor identifiers
LDRIVEENC = const(0)
RDRIVEENC = const(1)
LTOOLENC = const(2)
RTOOLENC = const(3)
COLOURSENS = const(4)
GYRO = const(5)
LDRIVEPOW = const(6)
RDRIVEPOW = const(7)
LTOOLPOW = const(8)
RTOOLPOW = const(9)
LDRIVECOR = const(10)
RDRIVECOR = const(11)
LTOOLCOR = const(12)
RTOOLCOR = const(13)
RIGHTBUTTON = const(18)
DRIVEENC = const(19)
DRIVESPEED = const(20)
LDRIVESPEED = const(21)
RDRIVESPEED = const(22)
LTOOLSPEED = const(23)
RTOOLSPEED = const(24)
TIME = const(25)
PREVTIME = const(26)

# Event types
EVENT_NONE = const(0)
EVENT_PLACEHOLDER = const(1)
EVENT_SENSORVALUE = const(2)
EVENT_MOTORSPEEDCONTROL = const(3)
EVENT_PIDGYRO = const(4)
EVENT_PIDLINE = const(5)
EVENT_PIDHOLD = const(6)
EVENT_TIMER = const(7)
EVENT_COMPUTEMOTORSTALL = const(8)
EVENT_HALT = const(9)

FUNC_CONST = const(9)
FUNC_LINEAR = const(10)
FUNC_QUADRATIC = const(11)

CONDITION_NONE = const(12)
CONDITION_PLACEHOLDER = const(13)
CONDITION_ISTERMINATED = const(14)
CONDITION_SENSORVALUE = const(15)
CONDITION_AND = const(16)
CONDITION_OR = const(17)
CONDITION_NOT = const(18)
CONDITIONS_STARTIMMEDIATELY = const(19)
CONDITION_STOPIMMEDIATELY = const(20)
 """


# Adjustable parameters
DEBUG = True
SPARSE_SENSOR_READING = True

# Fixed parameters for sensor and motor identifiers
LDRIVEENC = 0
RDRIVEENC = 1
LTOOLENC = 2
RTOOLENC = 3
COLOURSENS = 4
GYRO = 5
LDRIVEPOW = 6
RDRIVEPOW = 7
LTOOLPOW = 8
RTOOLPOW = 9
LDRIVECOR = 10
RDRIVECOR = 11
LTOOLCOR = 12
RTOOLCOR = 13
RIGHTBUTTON = 18
DRIVEENC = 19
DRIVESPEED = 20
LDRIVESPEED = 21
RDRIVESPEED = 22
LTOOLSPEED = 23
RTOOLSPEED = 24
TIME = 25
PREVTIME = 26

# Event types
EVENT_NONE = 0
EVENT_PLACEHOLDER = 1
EVENT_SENSORVALUE = 2
EVENT_MOTORSPEEDCONTROL = 3
EVENT_PIDGYRO = 4
EVENT_PIDLINE = 5
EVENT_PIDHOLD = 6
EVENT_TIMER = 7
EVENT_COMPUTEMOTORSTALL = 8
EVENT_HALT = 9

FUNC_CONST = 9
FUNC_LINEAR = 10
FUNC_QUADRATIC = 11

CONDITION_NONE = 12
CONDITION_PLACEHOLDER = 13
CONDITION_ISTERMINATED = 14
CONDITION_SENSORVALUE = 15
CONDITION_AND = 16
CONDITION_OR = 17
CONDITION_NOT = 18
CONDITIONS_STARTIMMEDIATELY = 19
CONDITION_STOPIMMEDIATELY = 20

SPEED_WINDOW = 5


# File path
TABLELENGTHSFILE = "instructions/tableLengths"
