
# Adjustable parameters
DEBUG_ = False
SPARSE_SENSOR_READING_ = True

# Fixed parameters for sensor and motor identifiers
LDRIVEENC = 0
RDRIVEENC = 1
LTOOLENC = 2
RTOOLENC = 3
COLOURSENS = 4
GYRO = 5
LDRIVEPOW = 6
RDRIVEPOW = 7
LTOOLPOW = 8
RTOOLPOW = 9
LDRIVECOR = 10
RDRIVECOR = 11
LTOOLCOR = 12
RTOOLCOR = 13
LDRIVEPOWPREV = 14
RDRIVEPOWPREV = 15
LTOOLPOWPREV = 16
RTOOLPOWPREV = 17
RIGHTBUTTON = 18
DRIVEENC = 19
DRIVESPEED = 20
LDRIVESPEED = 21
RDRIVESPEED = 22
LTOOLSPEED = 23
RTOOLSPEED = 24
TIME = 25
PREVTIME = 26
LDRIVEENCREAD = 27
RDRIVEENCREAD = 28
LTOOLENCREAD = 29
RTOOLENCREAD = 30
LDRIVESPEEDREAD = 31
RDRIVESPEEDREAD = 32
LTOOLSPEEDREAD = 33
RTOOLSPEEDREAD = 34
GYROREAD = 35
RIGHTBUTTONREAD = 36
DRIVEMOTORENCPREV = 37
GYROPREV = 38
GYROOFFSET = 39




# Event types
EVENT_NONE = 0
EVENT_PLACEHOLDER = 1
EVENT_SENSORVALUE = 2
EVENT_MOTORSPEEDCONTROL = 3
EVENT_PIDGYRO = 4
EVENT_PIDLINE = 5
EVENT_PIDHOLD = 6
EVENT_TIMER = 7
EVENT_COMPUTEMOTORSTALL = 8
EVENT_HALT = 9

FUNC_CONST = 9
FUNC_LINEAR = 10
FUNC_QUADRATIC = 11

CONDITION_NONE = 12
CONDITION_PLACEHOLDER = 13
CONDITION_ISTERMINATED = 14
CONDITION_SENSORVALUE = 15
CONDITION_AND = 16
CONDITION_OR = 17
CONDITION_NOT = 18
CONDITIONS_STARTIMMEDIATELY = 19
CONDITION_STOPIMMEDIATELY = 20

# File path
TABLELENGTHSFILE = "/flash/instructions/tableLengths"